### ISSUE TITLE
Publish v1

### ISSUE THREAD

**Issue by lukekarrys** [andyet/eslint-config-andyet-react#3]
- [x] Possibly discuss #1 and #2 
- [x] Test on more repos that @latentflip had in mind
- [x] Use those repos to iterate on any rules
- [x] Publish

**Comment by latentflip** [comment]
So here's the initial output from andyet/wholestory.co https://gist.github.com/latentflip/84aeec237f74cd21c61a

Now, I don't think i had linting setup, so I think a lot of these are just untidy code, will go through and tidy up and see what remaines.

**Comment by latentflip** [comment]
Okay, so here's the extra config I ended up tweaking to make stuff pass:

```
{
  "parser": "babel-eslint",

  "extends": ["andyet-react"],

  "env": {
    "browser": true
  },

  "rules": {
    "arrow-parens": [2, "always"],
    "arrow-body-style": 0,
    "space-before-function-paren": [2, {"anonymous": "always", "named": "never"}],
    "prefer-const": 0,
    "react/prop-types": 0,
    "react/jsx-boolean-value": [2, "never"],
    "react/jsx-curly-spacing": 0
  }
}
```

`babel-eslint@5.0.0-beta4` has worked okay for me so far for babel-6 integration

**Comment by latentflip** [comment]
Thoughts on some of the above, and other stuff:

# Thoughts
- `arrow-parens`: I've gone back and forth on this, and tend to prefer just leaving them in?
- `object-shorthand`: I can see this confusing people initially, but I think this is actually a good way to show what you can do
- `space-before-function-paren`: my brain's always done: `function () {` and `function foo() {` but I see that the backend lint has this rule too, so maybe I just deal with it, or we raise it there?
  
  ``` javascript
  //this also affects:
  {
    foo() {
      //...
    },
    bar () {
    }
  }
  ```
  
  with the space just looks too weird to me :(
- `arrow-body-style`: as needed makes sense to me, but it throws on this, which is annoying:
  
  ``` javascript
    return api.request({
      url: `/users/${userId}`,
      method: 'delete'
    }).catch((err) => {
      return Promise.reject({
        errorMessage: `Server error: ${err.message}`
      });
    });
  ```
  
  and not sure how I feel about:
  
  ``` javascript
    return api.request({
      url: `/users/${userId}`,
      method: 'delete'
    }).catch((err) => Promise.reject({
      errorMessage: `Server error: ${err.message}`
    }));
  ```
- `react/jsx-curly-spacing` - i agree with this, but this is a pattern I use a bit which it trips up on
  
  ``` javascript
  <div>
    {errorMessage &&
      <Message style='error'>{errorMessage}</Message>
    }
  </div>
  ```
- `comma-dangle` - I'd like to prefer allowing dangling commas, but maybe it's better not to given that it doesn't work everywhere (json, fn args)
- `no-undef` - bailing on setTimeout/clearTimeout
- `prefer-const` - in general I like this, the one place where it's an issue is destructuring, particularly in render() fns
  
  ``` javascript
  const {
    foo,
    bar,
    baz
  } = this.props;
  
  let {
    className
  } = this.props;
  
  className += 'foo';
  
  return <SomeComponent className={className} />
  ```
  
  Now, I don't actually mind that too much, the problem is if you also use object spread.
  
  ``` javascript
  // want to use foo to modify className, but don't want it in resulting props
  let {
    size,
    className,
    ...restProps
  } = this.props;
  
  className += `button-size-${size}`
  
  return <button {...restProps} className={className} />
  ```
  
  this will error, because size is a const, but if I move it to it's own thing, then `restProps` will contain it.
- `camelcase` - this is all fine until you talk to snake_case apis. Though, maybe we should be explicitly disabling it per line/file if so?
- `react/jsx-boolean-value` - I think I prefer never for this (i.e. `disabled` not `disabled={true}`)

**Comment by latentflip** [comment]
Oh, and I disabled `react/prop-types` because I was lazy more than anything and wanted this to pass. Could be convinced though :)

**Comment by lukekarrys** [comment]
After discussion with @latentflip:

> arrow-parens

Switching to "always"

> object-shorthand

Sticking with "always"

> space-before-function-paren

@latentflip convinced me `{ "anonymous": "always", "named": "never" }` is the way to go. This was also the only thing that was still breaking babel-eslint, so using that now too.

> arrow-body-style

Sticking with this. I prefer to write the case above with just removing the `return` statement and braces

``` js
 return api.request({
    url: `/users/${userId}`,
    method: 'delete'
  }).catch((err) =>
    Promise.reject({
      errorMessage: `Server error: ${err.message}`
    });
  );
```

> react/jsx-curly-spacing

Removing `allowMultiline` options since by default, braces spanning multiple lines are allowed with either setting.

> comma-dangle

Sticking with this.

> no-undef

Fixed with "browser: true" env

> prefer-const

Sticking with this. The case above should be disabled with `eslint-disable-line`

> camelcase

snake_case apis should be disabled per line

> react/jsx-boolean-value

Switching to never

> proptype/forbid-prop-types

Switching to warning for this.
